services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=messenger
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - CACHE_STORE=redis
      - QUEUE_CONNECTION=redis
      - BROADCAST_CONNECTION=reverb
    depends_on:
      - db
      - redis
    networks:
      - messenger-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - messenger-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - messenger-db-data:/var/lib/postgresql/data
    networks:
      - messenger-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - messenger-redis-data:/data
    networks:
      - messenger-network

networks:
  messenger-network:
    driver: bridge

volumes:
  messenger-db-data:
  messenger-redis-data:
